# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffa5b1b8e779a1458092021bbd3c1b558c6554ffe4ecdfbb002b4aebbf047128c14f0ce929d892478f602cce7e6214f71e35b271b8c4497d30f0c03b11e9800e

test:
  secret_key_base: 1cef483b4d011bc78876f997a1dae04c22638244b50fe886fea76c06948c056e23c7c2e19d77a427e293392add9388d90301b4395fde1be29fb9a6decd66d2a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
